// <auto-generated />
using ControleRotasMvc.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ControleRotasMvc.Migrations
{
    [DbContext(typeof(ControleRotasContext))]
    [Migration("20200117234355_CadastroEmpresa")]
    partial class CadastroEmpresa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ControleRotasMvc.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CpfResponsavel");

                    b.Property<string>("DiasAula");

                    b.Property<string>("Email");

                    b.Property<string>("EmailResponsavel");

                    b.Property<int>("EmpresaId");

                    b.Property<string>("Nome");

                    b.Property<string>("NomeResponsavel");

                    b.Property<int>("Situacao");

                    b.Property<string>("Telefone");

                    b.Property<string>("TelefoneResponsavel");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.DiasAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("DiasAula");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Documento");

                    b.Property<int>("HabilitarPagSeguro");

                    b.Property<string>("Nome");

                    b.Property<string>("ReponsavelTelefone");

                    b.Property<string>("Responsavel");

                    b.Property<string>("ResponsavelEmail");

                    b.Property<string>("emailPagseguro");

                    b.Property<string>("tokenPagSeguro");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Estado");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Numero");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<string>("Cor");

                    b.Property<string>("DaysOfWeek");

                    b.Property<string>("Descricao");

                    b.Property<int>("EmpresaId");

                    b.Property<DateTime>("End");

                    b.Property<int>("GroupId");

                    b.Property<bool>("IsFullDay");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<string>("BoletoBarcode");

                    b.Property<string>("BoletoCode");

                    b.Property<string>("BoletoPaymentLink");

                    b.Property<string>("BoletoVencimento");

                    b.Property<int>("EmpresaId");

                    b.Property<int>("FormaRecebimento");

                    b.Property<int>("Situacao");

                    b.Property<float>("Valor");

                    b.Property<DateTime>("Vencimento");

                    b.HasKey("Id");

                    b.ToTable("DocumentosFinanceiros");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmpresaId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.MateriaAlunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<int>("MateriaId");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("MateriaId");

                    b.ToTable("MateriaAlunos");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<float>("Bimestre1");

                    b.Property<float>("Bimestre2");

                    b.Property<float>("Bimestre3");

                    b.Property<float>("Bimestre4");

                    b.Property<string>("Materia");

                    b.Property<int>("MateriaId");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmpresaId");

                    b.Property<int>("Status");

                    b.Property<string>("UsuarioEmail");

                    b.Property<string>("UsuarioLogin");

                    b.Property<string>("UsuarioNome");

                    b.Property<string>("UsuarioSenha");

                    b.Property<string>("UsuarioSobrenome");

                    b.Property<int>("UsuarioTipo");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControleRotasMvc.Models.MateriaAlunos", b =>
                {
                    b.HasOne("ControleRotasMvc.Models.Aluno", "Aluno")
                        .WithMany("MateriaAlunos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ControleRotasMvc.Models.Materia", "Materia")
                        .WithMany("MateriaAlunos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ControleRotasMvc.Models.Nota", b =>
                {
                    b.HasOne("ControleRotasMvc.Models.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
